/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface ParkingDashboard {
        "hourlyRate": number;
        "maxCars": number;
        "startingRate": number;
    }
    interface ParkingFooter {
    }
    interface ParkingHeader {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLParkingDashboardElement extends Components.ParkingDashboard, HTMLStencilElement {
    }
    var HTMLParkingDashboardElement: {
        prototype: HTMLParkingDashboardElement;
        new (): HTMLParkingDashboardElement;
    };
    interface HTMLParkingFooterElement extends Components.ParkingFooter, HTMLStencilElement {
    }
    var HTMLParkingFooterElement: {
        prototype: HTMLParkingFooterElement;
        new (): HTMLParkingFooterElement;
    };
    interface HTMLParkingHeaderElement extends Components.ParkingHeader, HTMLStencilElement {
    }
    var HTMLParkingHeaderElement: {
        prototype: HTMLParkingHeaderElement;
        new (): HTMLParkingHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "parking-dashboard": HTMLParkingDashboardElement;
        "parking-footer": HTMLParkingFooterElement;
        "parking-header": HTMLParkingHeaderElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface ParkingDashboard {
        "hourlyRate": number;
        "maxCars": number;
        "startingRate": number;
    }
    interface ParkingFooter {
    }
    interface ParkingHeader {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "parking-dashboard": ParkingDashboard;
        "parking-footer": ParkingFooter;
        "parking-header": ParkingHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "parking-dashboard": LocalJSX.ParkingDashboard & JSXBase.HTMLAttributes<HTMLParkingDashboardElement>;
            "parking-footer": LocalJSX.ParkingFooter & JSXBase.HTMLAttributes<HTMLParkingFooterElement>;
            "parking-header": LocalJSX.ParkingHeader & JSXBase.HTMLAttributes<HTMLParkingHeaderElement>;
        }
    }
}
